# Generated by Django 2.2.5 on 2019-10-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edrpou', models.CharField(max_length=11, verbose_name='ЄДРПОУ:')),
                ('name', models.CharField(max_length=250, verbose_name='Назва компанії:')),
                ('address', models.CharField(max_length=250, verbose_name='Адреса компанії:')),
                ('contacts', models.CharField(max_length=250, verbose_name='Контакти компанії:')),
                ('koatuu', models.CharField(max_length=10)),
                ('tonnes_total', models.FloatField()),
                ('pzuv_total', models.FloatField()),
                ('tonnes_1', models.FloatField()),
                ('tonnes_2', models.FloatField()),
                ('tonnes_3', models.FloatField()),
                ('tonnes_4', models.FloatField()),
                ('tonnes_total_2015', models.FloatField()),
                ('pzuv_total_2015', models.FloatField()),
                ('tonnes_1_2015', models.FloatField()),
                ('tonnes_2_2015', models.FloatField()),
                ('tonnes_3_2015', models.FloatField()),
                ('tonnes_4_2015', models.FloatField()),
                ('tonnes_total_2016', models.FloatField()),
                ('pzuv_total_2016', models.FloatField()),
                ('tonnes_1_2016', models.FloatField()),
                ('tonnes_2_2016', models.FloatField()),
                ('tonnes_3_2016', models.FloatField()),
                ('tonnes_4_2016', models.FloatField()),
                ('tonnes_total_2017', models.FloatField()),
                ('pzuv_total_2017', models.FloatField()),
                ('tonnes_1_2017', models.FloatField()),
                ('tonnes_2_2017', models.FloatField()),
                ('tonnes_3_2017', models.FloatField()),
                ('tonnes_4_2017', models.FloatField()),
                ('tonnes_total_2018', models.FloatField()),
                ('pzuv_total_2018', models.FloatField()),
                ('tonnes_1_2018', models.FloatField()),
                ('tonnes_2_2018', models.FloatField()),
                ('tonnes_3_2018', models.FloatField()),
                ('tonnes_4_2018', models.FloatField()),
                ('tonnes_total_2019', models.FloatField()),
                ('pzuv_total_2019', models.FloatField()),
                ('tonnes_1_2019', models.FloatField()),
                ('tonnes_2_2019', models.FloatField()),
                ('tonnes_3_2019', models.FloatField()),
                ('tonnes_4_2019', models.FloatField()),
            ],
            options={
                'ordering': ['tonnes_total'],
            },
        ),
    ]
